//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageOfTheDay.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Days
    {
        public Days()
        {
            this.Messages = new HashSet<Messages>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Messages> Messages { get; set; }
    }
}
